### PR TITLE
Extend length of string datatypes in Skill

### PR DESCRIPTION
**Pull request by ngnmhieu**
The datatype of the columns 'description', 'implementation' and 'jhi_validation' is extended from 255 to 2048

### CODE REVIEW

**Comment by sberlin** [comment]
What about the corresponding entry in `master.xml`?

**Comment by ngnmhieu** [comment]
@sberlin somehow I didn't include it in the commit. Now it's added to master.xml

**Comment by sberlin** [comment]
Does the job, but not regenerating the entity with jHipster leads to exceptions in this case: adding or editing a skill with attributes longer than 2048 characters fails due to missing frontend/backend validations. The user does not get any information about the failure reason. @lriebandt Do we insist on further code generator usage to evolve our entity models?

**Comment by sberlin** [comment]
Had a talk with @lriebandt. We should keep using the generator, so please set the maxlength with the generator CLI and ignore the newly generated liquibase change set of the skill table in favor of the one you've already provided.

**Comment by ngnmhieu** [comment]
@sberlin the maxlength validation rules are now added

**Comment by sberlin** [comment]
@ngnmhieu The HTML5 validations are still missing.

**Comment by ngnmhieu** [comment]
@sberlin done!

**Comment by sberlin** [comment]
@ngnmhieu Thank you for the contribution!

**Pull request merged**
